<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="RabbitMQ.Client" Version="7.1.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\sample\Sample.Application\Sample.Application.csproj" />
    <ProjectReference Include="..\..\sample\Sample.Data\Sample.Data.csproj" />
    <ProjectReference Include="..\Codeed.Framework.AspNet\Codeed.Framework.AspNet.csproj" />
    <ProjectReference Include="..\Codeed.Framework.Data\Codeed.Framework.Data.csproj" />
  </ItemGroup>

</Project>
