name: Publish .NET NuGet packages

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'     
        required: true
        default: '0.0.0' 

jobs:
  build:
    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: 'net/Codeed.Framework.sln'
      
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v2.1.0
      with:
        dotnet-version: 9.0.x
      
    - name: Restore dependencies
      run: dotnet restore $SOLUTION
        
    - name: Build
      run: dotnet build $SOLUTION --configuration $BUILD_CONFIG -p:Version=${{ github.event.inputs.version }} --no-restore

    - name: Run tests
      run: dotnet test $SOLUTION --configuration $BUILD_CONFIG --no-restore --no-build --verbosity normal

    - name: Pack
      run: dotnet pack $SOLUTION --configuration $BUILD_CONFIG -p:PackageVersion=${{ github.event.inputs.version }} --no-restore --no-build

    - name: Publish Codeed.Framework packages
      run: |
        for pkg in $(find . -name "Codeed.Framework*.nupkg"); do
          echo "Publishing $pkg"
          dotnet nuget push "$pkg" --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json
        done
      
    - name: Create Tag
      uses: rickstaa/action-create-tag@v1
      with:
       tag: ${{ github.event.inputs.version }}
       message: "Version ${{ github.event.inputs.version }}"
